### ISSUE TITLE
Teraform resource "fusionauth_user_action" does not have webhook transaction properties.

### ISSUE THREAD

**Issue by sanjesh1000** [FusionAuth/fusionauth-theme-helper#11]
Hello FusionAuth Community,

I have been using the FusionAuth Terraform provider to manage my FusionAuth resources. While configuring user actions, I noticed that the "Webhook Transaction" property available in the FusionAuth UI is **not present in the Terraform provider.**

**Steps to Reproduce:**

Go to the FusionAuth UI.
Navigate to User Actions.
Observe the "Webhook Transaction" property.
Expected Behavior: The Terraform provider should support the "Webhook Transaction" property for user actions, allowing it to be configured via Terraform.

**Actual Behavior:** The "Webhook Transaction" property is not available in the Terraform provider for user actions.

```
resource "fusionauth_user_action" "example" {
  name        = "Example Action"
  description = "An example user action"
  # Missing property
  # webhook_transaction = .....options..
}
```

**Comment by mooreds** [comment]
Thanks @sanjesh1000 . Can you please file this issue against https://github.com/fusionauth/terraform-provider-fusionauth and close it out here?

**Comment by sanjesh1000** [comment]
ohk sorry, by mistake i opened here

**Comment by sanjesh1000** [comment]
This is related to fusionAuth Terraform Provider, by mistake, posted here, so closing it.

**Comment by mooreds** [comment]
Thanks!
