### ISSUE TITLE
defaultMessages returning additional backslash

### ISSUE THREAD

**Issue by jfaMan** [FusionAuth/fusionauth-theme-helper#2]
Hi,

I came across an issue where the escape backslashes are not being unescaped when creating `defaultMessages.txt` causing there to be an extra backslash in instances. In my case this affected anchor tags href attributes and unicode, which resulted in the output to be `href=\"https://site.com\"` and `\\u2026` respectively.

I added the following sed commands to line 12 of `download.sh` to fix it: `|sed 's/\\"/"/g' |sed 's/\\\\/\\/g'`

**Comment by mooreds** [comment]
Thanks for reporting this, @jfaMan !
