### ISSUE TITLE
`npx fusionauth theme:` commands are ignoring $TMP_DIR and targeting -h directory instead 

### ISSUE THREAD

**Issue by CodyMoore240** [FusionAuth/fusionauth-theme-helper#7]
exactly what the title says. I do not see a template to use so I apologize if this is in the wrong format.
![image](https://github.com/FusionAuth/fusionauth-theme-helper/assets/12897895/f030077c-e849-4d28-91f5-c8f64ff75ac5)

Any help would be appreciated!

**Comment by mooreds** [comment]
This is happening on a windows box using git bash.

**Comment by mooreds** [comment]
This worked for me on git bash with node 18. I did have to make the subdirectory manually. But was able to download then upload a theme.

It failed on node 14:

```
file:///C:/Users/path/work/fusionauth/fusionauth-theme-helper/node_modules/queue/index.js:8
export class QueueEvent extends Event {
                                ^

ReferenceError: Event is not defined
    at file:///C:/Users/path/work/fusionauth/fusionauth-theme-helper/node_modules/queue/index.js:8:33
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by mooreds** [comment]
@CodyMoore240 what version of node are you using?

**Comment by mooreds** [comment]
Also, if you are only looking to upload theme files from `src`, you could use the node cli directly: https://www.npmjs.com/package/@fusionauth/cli

**Comment by ColinFrick** [comment]
Is this still open?

**Comment by mooreds** [comment]
@CodyMoore240 did this get resolved on your end?

**Comment by mooreds** [comment]
Closing because I believe this is resolved. @CodyMoore240 if I'm wrong, please re-open.
