### ISSUE TITLE
watch.sh script is not completing the file upload successfully

### ISSUE THREAD

**Issue by labiang** [FusionAuth/fusionauth-theme-helper#9]
Hi everyone - the `watch` script is not completing the upload whenever a file changes locally.

It gets stuck on the `Uploading {DIR_NAME}` step

To reproduce, just run the watch script and try to trigger the file upload.

<img width="1033" alt="image" src="https://github.com/FusionAuth/fusionauth-theme-helper/assets/11696114/23ee964b-4aa0-42bf-b9f4-25f0a495d271">

**Comment by ColinFrick** [comment]
Hi @itstriolink 

Does it really get stuck? It only outputs something after the `Uploading` line if it fails.
Maybe this could be improved. 

Edit: I have extended the cli with a status update:
<img width="654" alt="image" src="https://github.com/FusionAuth/fusionauth-theme-helper/assets/5517677/98769c5a-9022-4134-be98-ecae46615b67">

It should be included with the next release.

**Comment by labiang** [comment]
@ColinFrick If that's the case then I'd like if it would be improved.

The thing is that when you use the upload script, you get a success message, and while you use the watch script, it does not give you that (uniform behaviour). This automatically makes me think that something is wrong with the script/command.

Also, the message says "uploading", which means something is in progress, and hasn't completed yet, which is also misleading.

These are all my opinion but what you suggested on the screenshot there seems MUCH better and clearer.

Thanks for your response.
